apiVersion: v1
kind: PersistentVolume
metadata:
  name: apache-pv
  namespace: apache
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data