apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apache-pvc
  namespace: apache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
  